# Generated by Django 5.1 on 2024-09-20 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='property',
            name='check_out',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.usertype'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'room')},
        ),
    ]
