# Generated by Django 5.1 on 2024-09-20 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_property_check_in_remove_property_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.country'),
        ),
    ]
